apiVersion: v1
kind: Pod
metadata:
  name: pvc-debug
  namespace: prefect
spec:
  restartPolicy: Never
  containers:
    - name: debug
      image: busybox:1.36
      command: ["sh", "-c", "sleep 1d"]
      volumeMounts:
        - name: pvc
          mountPath: /data
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: prefect-shared-pvc
