apiVersion: v1
kind: ServiceAccount
metadata:
  name: prefect-flow-runner
  namespace: prefect
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-flow-runner
  namespace: prefect
rules:
  # Create/observe the child Jobs you spawn (dummy tasks)
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]

  # Needed to wait for pods + optionally fetch logs
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-flow-runner
  namespace: prefect
subjects:
  - kind: ServiceAccount
    name: prefect-flow-runner
    namespace: prefect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prefect-flow-runner