apiVersion: batch/v1
kind: Job
metadata:
  name: prefect-random-grep-scatter-deploy
  namespace: prefect
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: prefect-deploy
          image: <registry>/random-grep-scatter:0.1.0
          imagePullPolicy: IfNotPresent
          command: ["python", "deploy.py"]
          env:
            - name: PREFECT_API_URL
              value: "http://prefect-server.prefect.svc.cluster.local:4200/api"
            - name: PREFECT_IMAGE
              value: "brunifrancesco/random-grep-scatter:0.1.0"
            - name: PREFECT_WORK_POOL
              value: "local-k8s"
            - name: PREFECT_DEPLOYMENT_NAME
              value: "random-grep-count-scatter"
